-- MySQL Script generated by MySQL Workbench
-- Sun Aug 16 14:56:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`principal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`principal` (
  `principal_id` INT NOT NULL AUTO_INCREMENT,
  `user` MEDIUMTEXT NOT NULL,
  `pass` MEDIUMTEXT NOT NULL,
  `cls_fkey` LONGTEXT NOT NULL,
  PRIMARY KEY (`principal_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`standard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`standard` (
  `standard_id` INT NOT NULL AUTO_INCREMENT,
  `class` VARCHAR(30) NOT NULL,
  `email` MEDIUMTEXT NOT NULL,
  `password` MEDIUMTEXT NOT NULL,
  `no_of_students` INT NOT NULL,
  `date` DATE NOT NULL,
  `students_fkey` LONGTEXT NOT NULL,
  PRIMARY KEY (`standard_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `roll_no` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(10) NOT NULL,
  `question_fkey` LONGTEXT NOT NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
  `questions_id` INT NOT NULL AUTO_INCREMENT,
	`B1.1` VARCHAR(6) NOT NULL,
`B1.1_f` LONGTEXT NULL,
`B2.1` VARCHAR(6) NOT NULL,
`B2.1_f` LONGTEXT NULL,
`B3.1` VARCHAR(6) NOT NULL,
`B3.1_f` LONGTEXT NULL,
`B4.1` VARCHAR(6) NOT NULL,
`B4.1_f` LONGTEXT NULL,
`B5.1` VARCHAR(6) NOT NULL,
`B5.1_f` LONGTEXT NULL,
`T1.1` VARCHAR(6) NOT NULL,
`T1.1_f` LONGTEXT NULL,
`T2.1` VARCHAR(6) NOT NULL,
`T2.1_f` LONGTEXT NULL,
`T3.1` VARCHAR(6) NOT NULL,
`T3.1_f` LONGTEXT NULL,
`T4.1` VARCHAR(6) NOT NULL,
`T4.1_f` LONGTEXT NULL,
`T5.1` VARCHAR(6) NOT NULL,
`T5.1_f` LONGTEXT NULL,
`V1.1` VARCHAR(6) NOT NULL,
`V1.1_f` LONGTEXT NULL,
`V2.1` VARCHAR(6) NOT NULL,
`V2.1_f` LONGTEXT NULL,
`V3.1` VARCHAR(6) NOT NULL,
`V3.1_f` LONGTEXT NULL,
`V4.1` VARCHAR(6) NOT NULL,
`V4.1_f` LONGTEXT NULL,
`V5.1` VARCHAR(6) NOT NULL,
`V5.1_f` LONGTEXT NULL,
  PRIMARY KEY (`questions_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
